networks:
  app-network:
    driver: bridge

services:
  mongodb:
    image: mongo:7.0
    container_name: message_db
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_AUTH_MECHANISM=${MONGO_AUTH_MECHANISM}
    volumes:
      - mongodb_data:/data/db
    command:
      - "--auth"
      - "--wiredTigerCacheSizeGB=0.5"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message_app
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
