version: '3'

env:
  ENV: development

dotenv: 
  - .env

tasks:
  build:
    cmds:
      - go build -o ${BINARY} ./cmd/app/
    desc: Build the Go application.

  start:
    cmds:
      - ./cmd/app/
    desc: Run the Go application.

  restart:
    cmds:
      - task build
      - task start
    desc: Restart the Go application.

  test:
    cmds:
      - go test ./...
    desc: Run all tests.

  lint:
    cmds:
      - golangci-lint run
    desc: Run linters on the codebase.